VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant::configure("2") do |config|
    config.vm.box = "phusion/ubuntu-14.04-amd64"
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
        v.name = "Ubuntu_VM"
    end
    
    config.vm.provision "docker" do |d|
        d.pull_images "node"
    end
end
