VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant::configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "phusion/ubuntu-14.04-amd64"

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
        v.name = "Ubuntu_VM"
		v.gui = true
    end

    config.vm.provision "file", source: "configure.sh", destination: "configure.sh"
    config.vm.provision "shell", inline: "/bin/bash ./configure.sh"
end