VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant::configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "app" do |v|
		v.vm.provider "docker" do |d|
			d.build_dir       = "./docker"
			d.cmd             = ["ls", "/app"]
			d.remains_running = false
		end
	end
	
	config.vm.define "db" do |v|
		v.vm.provider "docker" do |d|
			d.image = "paintedfox/postgresql"
		end
	end
end